replicaCount: 1

image:
  repository: ""
  tag: latest
  pullPolicy: Always

clusterName: ""

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 128Mi

serviceAccount:
  create: true

rbac:
  create: true
