apiVersion: apps/v1
kind: Deployment
metadata:
  name: scam
  namespace: scam
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: scam
  template:
    metadata:
      labels:
        app: scam
    spec:
      serviceAccountName: scam
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: scam
          image: ghcr.io/norskhelsenett/scam:latest
          imagePullPolicy: Always
          env:
            - name: CLUSTER_NAME
              value: "talos-proxmox-cluster"
            - name: GOGC
              value: "50"
            - name: GOMEMLIMIT
              value: "96MiB"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
          securityContext:
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
