apiVersion: v1
kind: Namespace
metadata:
  name: spam-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spam-operator
  namespace: spam-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spam-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spam-operator
subjects:
  - kind: ServiceAccount
    name: spam-operator
    namespace: spam-operator
roleRef:
  kind: ClusterRole
  name: spam-operator
  apiGroup: rbac.authorization.k8s.io
